version: '3'

services:
  web:
    image: stackexchange
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  db:
    # restart: always
    image: postgres:latest
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}