version: '3'

services:
  web:
    restart: always
    image: stackexchange
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db
    env_file: .env
    command: alembic -c stackexchange_app/alembic.ini upgrade head
  db:
    image: postgres:latest
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}