"""Init db

Revision ID: db8831f80b07
Revises: 
Create Date: 2020-09-05 16:41:23.544023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db8831f80b07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stackexchange_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_stackexchange_id'), 'questions', ['stackexchange_id'], unique=True)
    op.create_table('topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.String(length=300), nullable=False),
    sa.Column('questions_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_topic'), 'topics', ['topic'], unique=True)
    op.create_table('topics_questions',
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('topic_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], )
    )
    op.create_index(op.f('ix_topics_questions_question_id'), 'topics_questions', ['question_id'], unique=False)
    op.create_index(op.f('ix_topics_questions_topic_id'), 'topics_questions', ['topic_id'], unique=False)
    op.create_index(op.f('ix_topics_questions_topic_number'), 'topics_questions', ['topic_number'], unique=False)
    op.create_index('uix_topics_questions', 'topics_questions', ['topic_id', 'question_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix_topics_questions', table_name='topics_questions')
    op.drop_index(op.f('ix_topics_questions_topic_number'), table_name='topics_questions')
    op.drop_index(op.f('ix_topics_questions_topic_id'), table_name='topics_questions')
    op.drop_index(op.f('ix_topics_questions_question_id'), table_name='topics_questions')
    op.drop_table('topics_questions')
    op.drop_index(op.f('ix_topics_topic'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_questions_stackexchange_id'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
